markdown: NullConverter

exclude:
  - release-scripts
  - LICENSE
  - Makefile
  - README.md
  - RELEASING.md
  - BUILDING_CALICO.md
  - CONTRIBUTING_DOCS.md
  - CONTRIBUTING_CODE.md
  - DOC_STYLE_GUIDE.md
  - hack
  - calico_node
  - v1.5
  - v1.6
  - v2.0
  - v2.1
  - v2.2
  - v2.3
  - v2.4
  - v2.5
  - v2.6
  - v3.0
  - v3.1
  - v3.2
  - v3.3
  - v3.4
