[[constraint]]
  name = "k8s.io/api"
  branch = "release-1.10"

[[constraint]]
  name = "k8s.io/client-go"
  branch = "release-7.0"

[[override]]
  name = "k8s.io/apimachinery"
  revision = "d49e237a2683fa6dc43a86c7b1b766e0219fb6e7"

[prune]
  go-tests = true
  unused-packages = true
