# Settings in the [build] context are global and are applied to all contexts unless otherwise overridden by more specific contexts.
# The cp, bundle install and bundle exec parts are only required to work around not being able to put the Gemfile int he root directory. It can't go in the root because that breaks the jekyll/jekyll container.
[build]
  command = 'make netlify'

# Deploy Preview context: All Deploy Previews will inherit these settings.
# Override the build command to include the Preview URL
[context.deploy-preview]
  command = 'echo "url: $DEPLOY_PRIME_URL" >_config_url.yml; DEV=true make netlify'

[[headers]]
  for = "/*.yaml"
  [headers.values]
    content-type = "text/yaml"

[[headers]]
  for = "/*.yml"
  [headers.values]
    content-type = "text/yaml"

[[headers]]
  for = "/*.sh"
  [headers.values]
    content-type = "text/x-shellscript"

[[headers]]
  for = "/*.bash"
  [headers.values]
    content-type = "text/x-shellscript"