# Select which datastore mode. Can be 'etcd' or 'kdd'.
# Note: Changing this after installation is not supported. 
datastore: kdd

# Config for etcd
etcd:
  # Endpoints for the etcd instances. This can be a comma separated list of endpoints.
  endpoints: null
  # Authentication information for accessing secure etcd instances.
  tls:
    crt: null
    ca: null
    key: null

# Sets the networking mode. Can be 'calico', 'flannel', or 'none'
network: calico

calico_ipam: true
app_layer_policy: false

# initialPool configures the pool used by Calico when using calico-ipam.
# Note that these settings are only applied during initial install.
# Changing these settings post-install will have no effect.
initialPool:
  # The default IPv4 pool to create on startup if none exists. Pod IPs will be
  # chosen from this range. Changing this value after installation will have
  # no effect. This should fall within `--cluster-cidr`.
  cidr: "192.168.0.0/16"

  # Can be "None", "CrossSubnet", or "Always"
  ipIpMode: Always
