{{- /*
calico.yaml acccepts the following include flags:

| Name             | Accepted Values          |
|------------------|--------------------------|
| datastore        | kdd, etcd                |
| typha            | true, false              |
| network          | calico, flannel, <unset> |
| calico_ipam      | true, false              |
| variant_name     | Calico, Canal            |
| app_layer_policy | true, false              |

*/ -}}
{% capture variant_name %}{% if .Values.network == "flannel" %}Canal{% else %}Calico{{ end }}{% endcapture -%}
# {{variant_name}} Version {{site.data.versions[page.version].first.title}}
# {{site.url}}/{{page.version}}/releases#{{site.data.versions[page.version].first.title}}
# This manifest includes the following component versions:
#   {{.Values.nodecontainer}}:{{.Values.node.tag}}
#   calico/cni:{{.Values.cni.tag}}
{{- if eq .Values.datastore "etcd" }}
#   calico/kube-controllers:{{.Values.kubeControllers.tag}}
{{- end }}
{{- if eq .Values.network "flannel" }}
#   coreos/flannel:{{.Values.flannel.tag}}
{{- end }}

{% include {{page.version}}/manifests/calico-config.yaml datastore=.Values.datastore network=.Values.network calico_ipam=.Values.calico_ipam variant_name=variant_name typha=.Values.typha %}
---
{% if .Values.datastore == "etcd" %}
{% include {{page.version}}/manifests/calico-etcd-secrets.yaml %}
---
{%- elsif .Values.datastore == "kdd" and .Values.typha == "true" %}
{% include {{page.version}}/manifests/calico-typha.yaml %}
---
{{- end }}
{% include {{page.version}}/manifests/calico-node.yaml datastore=.Values.datastore network=.Values.network variant_name=variant_name typha=.Values.typha app_layer_policy=.Values.app_layer_policy %}
---
{{- if and (eq .Values.datastore "etcd") (eq .Values.network "flannel") }}
{% include {{page.version}}/manifests/configure-canal.yaml %}
---
{{- end }}
{{- if eq .Values.datastore "etcd" }}
{% include {{page.version}}/manifests/calico-kube-controllers.yaml variant_name=variant_name %}
{{- else if eq .Values.datastore "kdd" }}
{% include {{page.version}}/manifests/kdd-crds.yaml network=.Values.network %}
{{- end -}}
---
{% include {{page.version}}/manifests/rbac.yaml datastore=.Values.datastore network=.Values.network calico_ipam=.Values.calico_ipam variant_name=variant_name typha=.Values.typha %}
