kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: calico-operator-admin
subjects:
- kind: ServiceAccount
  name: calico-operator
  # Replace this with the namespace the operator is deployed in.
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
