apiVersion: apps/v1
kind: Deployment
metadata:
  name: calico-operator
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      name: calico-operator
  template:
    metadata:
      labels:
        name: calico-operator
    spec:
      serviceAccountName: calico-operator
      hostNetwork: true
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      - key: node.kubernetes.io/not-ready
        operator: "Exists"
        effect: NoSchedule
      containers:
        - name: calico-operator
          # Replace this with the built image name
          image: gcr.io/tigera-dev/experimental/turk/calico-operator
          ports:
          - containerPort: 60000
            name: metrics
          imagePullPolicy: IfNotPresent
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: OPERATOR_NAME
              value: "calico-operator"
